// Manually defined types from Prisma schema

// Permission types for channel roles
export enum PermissionType {
  SEND_MESSAGES = "SEND_MESSAGES",
  MANAGE_MESSAGES = "MANAGE_MESSAGES",
  MANAGE_CHANNELS = "MANAGE_CHANNELS",
  MANAGE_ROLES = "MANAGE_ROLES",
  KICK_MEMBERS = "KICK_MEMBERS",
  BAN_MEMBERS = "BAN_MEMBERS",
  INVITE_MEMBERS = "INVITE_MEMBERS",
  PIN_MESSAGES = "PIN_MESSAGES",
  MANAGE_WEBHOOKS = "MANAGE_WEBHOOKS",
  ADD_REACTIONS = "ADD_REACTIONS",
  ATTACH_FILES = "ATTACH_FILES",
  EMBED_LINKS = "EMBED_LINKS",
  MENTION_EVERYONE = "MENTION_EVERYONE",
  CHANGE_NICKNAME = "CHANGE_NICKNAME",
  MANAGE_NICKNAMES = "MANAGE_NICKNAMES",
  VIEW_CHANNELS = "VIEW_CHANNELS",
  CONNECT_VOICE = "CONNECT_VOICE",
  SPEAK_VOICE = "SPEAK_VOICE",
  STREAM_VIDEO = "STREAM_VIDEO",
  PRIORITY_SPEAKER = "PRIORITY_SPEAKER",
  VIEW_AUDIT_LOG = "VIEW_AUDIT_LOG",
  MODERATE_MEMBERS = "MODERATE_MEMBERS",
  MANAGE_EMOJIS = "MANAGE_EMOJIS",
  ADMINISTRATOR = "ADMINISTRATOR"
}

// Role template types
export enum RoleTemplateType {
  OWNER = "OWNER",
  ADMIN = "ADMIN",
  MODERATOR = "MODERATOR",
  MEMBER = "MEMBER",
  GUEST = "GUEST",
  CUSTOM = "CUSTOM"
} 